# Generated by Django 3.1.5 on 2021-01-31 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_name', models.CharField(max_length=100, verbose_name='Name')),
                ('author_description', models.CharField(max_length=400, verbose_name='Description')),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre_name', models.CharField(max_length=100, verbose_name='Name')),
                ('genre_description', models.CharField(max_length=400, verbose_name='Description')),
            ],
        ),
        migrations.CreateModel(
            name='Publishing_house',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publishing_house_name', models.CharField(max_length=100, verbose_name='Name')),
                ('publishing_house_description', models.CharField(max_length=400, verbose_name='Description')),
            ],
        ),
        migrations.CreateModel(
            name='Series',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('series_name', models.CharField(max_length=100, verbose_name='Name')),
                ('series_description', models.CharField(max_length=400, verbose_name='Description')),
            ],
        ),
    ]
