# Generated by Django 3.1.5 on 2021-03-21 19:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_name', models.CharField(max_length=100, verbose_name='Name')),
                ('book_picture', models.CharField(max_length=100, verbose_name='Picture')),
                ('book_price', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Price')),
                ('book_year_published', models.IntegerField(verbose_name='Year of publishing')),
                ('book_pages', models.IntegerField(verbose_name='Numb of pages')),
                ('book_binding', models.CharField(max_length=50, verbose_name='Binding')),
                ('book_format', models.CharField(max_length=50, verbose_name='Format')),
                ('book_isbn', models.CharField(max_length=50, verbose_name='ISBN')),
                ('book_weight', models.IntegerField(verbose_name='Weight')),
                ('book_age_limit', models.CharField(max_length=30, verbose_name='Age limits')),
                ('book_quantity', models.IntegerField(verbose_name='Quantity')),
                ('book_activity', models.CharField(max_length=10, verbose_name='Activity')),
                ('book_rating', models.IntegerField(verbose_name='Rating')),
                ('book_entry', models.DateField(verbose_name='Date of entry')),
                ('book_changes', models.DateField(verbose_name='Last changes')),
                ('book_author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book.author', verbose_name='Author')),
                ('book_genre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book.genre', verbose_name='Genre')),
                ('book_publishing_house', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book.publishing_house', verbose_name='Publishing house')),
                ('book_series', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book.series', verbose_name='Series')),
            ],
        ),
    ]
