# Generated by Django 3.1.5 on 2021-03-21 19:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_book'),
        ('cart', '0003_auto_20210321_2106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookincart',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='book.book', verbose_name='Book in a cart'),
        ),
    ]
